# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

acf_to_sigma <- function(acf) {
    .Call(`_gmwmx_acf_to_sigma`, acf)
}

autocovariance_to_wv <- function(acf, tau) {
    .Call(`_gmwmx_autocovariance_to_wv`, acf, tau)
}

powerlaw_autocovariance <- function(theta, n) {
    .Call(`_gmwmx_powerlaw_autocovariance`, theta, n)
}

