# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Sigma matrix given an acf vector
#' 
#' @param acf A \code{vector} specifying the autocovariance vector.
acf_to_sigma <- function(acf) {
    .Call(`_gmwmx_acf_to_sigma`, acf)
}

#'  Subset range of a vector
NULL

#'  Vectorized exponentiation
NULL

#' Compute the theoretical WV given the autocovariance vector 
#' 
#' @param acf A \code{vector} specifying the autocovariance vector
#' @param tau A \code{vector} of Wavelet Variance scales
autocovariance_to_wv <- function(acf, tau) {
    .Call(`_gmwmx_autocovariance_to_wv`, acf, tau)
}

#' Compute the power law autocovariance vector
#' @param theta A \code{vector} of length 2 specifying the parameters of the powerlaw process
#' @param n A \code{scalar} specifying the length of the signal
powerlaw_autocovariance <- function(theta, n) {
    .Call(`_gmwmx_powerlaw_autocovariance`, theta, n)
}

